---
- import_playbook: java.yaml
- name: install utils
  become: yes
  tasks:
    - name: install utils
      ansible.builtin.package:
        name: "{{ item }}"
      loop:
        - git
        - tree
        - nano
   